### ISSUE TITLE
Tracing disappears after restTemplate.exchange call

### ISSUE THREAD

**Issue by monnetchr** [spring-cloud-incubator/spring-cloud-sleuth-otel#22]
**Describe the bug**
I'm using the latests Spring Boot 2.4.3, Spring Cloud 2020.0.1 and Spring Cloud Sleuth OTel 1.0.0-M4 as described here https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel#quick-start
For propagation I use "type: W3C" in the config of Sleuth.
I have an MVC endpoint and within it, I use a RestTemplate to call another service which expects a traceparent header.
When I do an HTTP call on the endpoint, I can see traceId/spanId in the logs.
When the app calls the other service, on the wire I can see a traceparent header, and the other service indeed reuses the same traceId, so up to that point it all works as expected.
But when the `restTemplate.exchange` call is done, there is no traceId/spanId anymore.
Here is an extract from the logs:
```
2021-02-23 10:29:54.874 DEBUG [http-nio-8080-exec-6] o.s.w.c.RestTemplate.debug HTTP GET https://httpbin.org/get traceId=a2d2ec295687b6956049721e61cfca7c spanId=23e9d443a8d488f1
...
2021-02-23 10:29:56.204 DEBUG [http-nio-8080-exec-6] o.s.w.c.RestTemplate.debug Response 200 OK traceId= spanId=
```
For reference: https://gitter.im/spring-cloud/spring-cloud-sleuth?at=6034cd9b93539e234393522f

**Sample**
See https://github.com/monnetchr/otel-issue
Start with `mvn spring-boot:run` and then with `curl localhost:8080/demo` you can reproduce the problem.

**Comment by jonatan-ivanov** [comment]
@monnetchr Since even the section where the tracing information is supposed to be is invisible, I'm not sure this is a Sleuth-OTel issue. I feel it is more likely that this is a misconfiguration or a Sleuth issue.

By default, your log entries should look something like this:
`2020-04-09 17:45:40.516 ERROR [backend,5e8eeec48b08e26882aba313eb08f0a4,dcc1df555b5777b3] 97203 --- [nio-9000-exec-1] ...`
or if the tracing information is missing, you should see something like:
`2020-04-09 17:45:40.516 ERROR [backend,,] 97203 --- [nio-9000-exec-1] ...`
But the placeholder should be there. Do you see the tracing information for any log entry in this app?

Looking at your [logback config](https://github.com/monnetchr/otel-issue/blob/master/src/main/resources/logback-spring.xml#L5), it seems you are overriding the pattern which could be the issue. Could you please try out what happen if you:
1. Set the app name, e.g.: `spring.application.name: my-service`
2. Delete the `logback-spring.xml` file entirely and set the log level from the `application.yml`, e.g.: `logging.level.com.example: DEBUG`

If this works, you can check [how to override](https://github.com/jonatan-ivanov/teahouse/blob/f73b6035e35ea2df87e40368297278dde1a1b689/tea-service/src/main/resources/logback-spring.xml#L4) default spring config or [how to build your own from scratch but keeping the tracing info there](https://stackoverflow.com/questions/65846859/how-spring-cloud-sleuth-adds-tracing-information-to-logback-log-lines).
Please also check the [docs](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/#features-log-integration)

**Comment by monnetchr** [comment]
Here is how it looks like with your suggestions:
```
2021-02-26 07:30:38.702  INFO [otel-issue,9fa79cbbf43a3690f77a2706c8c24b09,c03182137948358c] 6576 --- [nio-8080-exec-1] com.example.demo.web.DemoEndpoint        : demo start, we have traceId/spanId in MDC:
...
2021-02-26 07:30:39.321  INFO [otel-issue,,] 6576 --- [nio-8080-exec-1] com.example.demo.web.DemoEndpoint        : demo end, where is traceId/spanId in MDC?
```

I think this ticket is a duplicate of #23 as the symptoms are the same: empty MDC context after a span. I'll verify once #23 is fixed.

**Comment by jonatan-ivanov** [comment]
@monnetchr Yepp, after you fixed the log config issue, this seems like the same as #23.
Let me close this in favor of that (there's already a PR for the issue), if it won't fix this, just ping me and we can reopen.
