### ISSUE TITLE
Library compatibility matrix

### ISSUE THREAD

**Issue by gquintana** [spring-cloud-incubator/spring-cloud-sleuth-otel#78]
**Is your feature request related to a problem? Please describe.**
I am trying to setup this library with sample application, but I can not figure out what's wrong with my Maven dependencies:
```
java.lang.UnsupportedOperationException: null
	at org.springframework.http.ReadOnlyHttpHeaders.set(ReadOnlyHttpHeaders.java:106) ~[spring-web-5.3.9.jar:5.3.9]
	at io.opentelemetry.extension.trace.propagation.B3PropagatorInjectorSingleHeader.inject(B3PropagatorInjectorSingleHeader.java:63) ~[opentelemetry-extension-trace-propagators-1.5.0.jar:1.5.0]
	at io.opentelemetry.extension.trace.propagation.B3Propagator.inject(B3Propagator.java:111) ~[opentelemetry-extension-trace-propagators-1.5.0.jar:1.5.0]
	at org.springframework.cloud.sleuth.otel.propagation.CompositeTextMapPropagator.lambda$inject$3(CompositeTextMapPropagator.java:113) ~[spring-cloud-sleuth-otel-1.1.0-M1.jar:1.1.0-M1]
```
There must be something incompatible between  opentelemetry and spring.

**Describe the solution you'd like**

I'd like to have a table showing which libraries versions are known to be compatible: 
* spring-cloud-sleuth-otel
* spring-cloud
* spring-core / spring-boot
* opentelemetry

**Describe alternatives you've considered**
I am following the documentation https://spring-cloud-incubator.github.io/spring-cloud-sleuth-otel/docs/current/reference/html/getting-started.html#getting-started-first-application-pom but I don't want to set a parent project

**Comment by jonatan-ivanov** [comment]
@gquintana Instead of setting a parent, adding the Spring Boot BOM in the example and not setting versions should resolve this issue.

We do have a compatibility matrix between Spring Boot and Spring Cloud: https://spring.io/projects/spring-cloud#adding-spring-cloud-to-an-existing-spring-boot-application
Everything else is governed by the BOMs so you don't need to set versions for your dependencies, you only need to define versions for your BOMs:
- [Spring Boot BOM](https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies)
- [Spring Cloud BOM](https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-dependencies)
- [Spring Cloud Sleuth OTel BOM](https://repo.spring.io/ui/native/milestone/org/springframework/cloud/spring-cloud-sleuth-otel-dependencies)

Based on the above, you can use the following BOMs together, these will cover everything you mentioned above:
- `org.springframework.boot:spring-boot-dependencies:2.5.4`
- `org.springframework.cloud:spring-cloud-dependencies:2020.0.3`
- `org.springframework.cloud:spring-cloud-sleuth-otel-dependencies:1.0.0-M10`

I'm going to add something like this to the readme of this project (this won't be needed after Sleuth OTel goes GA since it will be in the Spring Cloud BOM) and close this issue, please let me know if you want us to reopen:
- spring-cloud-sleuth-otel 1.0.x is compatible with spring-cloud 2020.x
- spring-cloud-sleuth-otel 1.1.x is compatible with spring-cloud 2021.x
